POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "feng@test.com",
    "password": "whatthefeng"
}
###
POST http://localhost:3000/api/operatore/login
Content-Type: application/json

{
    "username" : "aa",
    "pass" : "bb"
}

###
POST http://localhost:3000/api/cittadino/register 
Content-Type: application/json                    

{
    "nome" : "aaaa",
    "cognome" : "bbbb",
    "age" : 100,
    "genere" : "Uomo",
    "categoria" : "Lavoratore",
    "email" : "abc@gmail.com",
    "password" : "12345"
}

###

GET http://localhost:3000/users/getAll
Content-Type: application/json 

### 

GET http://localhost:3000/users/getById/69271f4f9e5aa630a457bfc8
Content-Type: application/json 

###

GET http://localhost:3000/users/getByEmail/feng@test.com
Content-Type: application/json 

####

GET http://localhost:3000/users/getByUsername/feng
Content-Type: application/json 

### 
GET http://localhost:3000/users/getFiltered?loggedIn=true
Content-Type: application/json 

###

GET http://localhost:3000/users/search?query=fe
Content-Type: application/json

###

GET http://localhost:3000/users/me
Content-Type: application/json
x-user-id: 69271f4f9e5aa630a457bfc8

###

GET http://localhost:3000/users/check-username/feng
Content-Type: application/json

###

GET http://localhost:3000/users/check-email/feng@test.com
Content-Type: application/json

###

GET http://localhost:3000/auth/status
Content-Type: application/json
Cookie: connect.sid=s%3APp4t4n0yfQXU67TNikmXO4ByPpvfxDy3.ArJwGYGMwvrcvJ1sDGYBLMQ88jk9bI7wmsw8E8upOZE
###

POST http://localhost:3000/auth/logout
Content-Type: application/json
Cookie: connect.sid=s%3APp4t4n0yfQXU67TNikmXO4ByPpvfxDy3.ArJwGYGMwvrcvJ1sDGYBLMQ88jk9bI7wmsw8E8upOZE