### Completa profilo cittadino
POST http://localhost:3000/auth/complete-profile
Content-Type: application/json
Authorization: Bearer {{TOKEN_CITTADINO}}

{
    "dataNascita": "1995-06-15",
    "circoscrizione": "Centro storico - Piedicastello",
    "genere": "Uomo",
    "categoria" : "Studente"
}

### Profilo cittadino autenticato
GET http://localhost:3000/cittadino/profile
Authorization: Bearer {{TOKEN_CITTADINO}}