### Completa profilo cittadino
POST http://localhost:3000/auth/complete-profile
Content-Type: application/json

{
    "cittadinoId" : "69341b68fa01c0233f64f56d",
    "nome" : "SubZero",
    "cognome" : "LDAOKWODA",
    "eta": 67,
    "genere": "Uomo",
    "categoria" : "Studente"
}

### Profilo cittadino autenticato
GET http://localhost:3000/cittadino/profile
Authorization: Bearer {{TOKEN_CITTADINO}}