### Creazione votazione (operatore autenticato)
POST http://localhost:3000/votazioni
Content-Type: application/json
Authorization: Bearer {{TOKEN_OPERATORE}}

{
  "titoloVotazione": "Votazione di test",
  "descrizione": "Descrizione breve di test",
  "data_inizio": "2025-12-10T09:00:00.000Z",
  "data_fine": "2025-12-20T18:00:00.000Z",
  "data_discussione": "2025-12-08T18:00:00.000Z",
  "domanda": {
    "titolo": "Sei favorevole alla proposta X?",
    "tipo": "risposta_singola",
    "opzioni": [
      { "testo": "Sì" },
      { "testo": "No" }
    ]
  }
}

### Lista votazioni dell'operatore
GET http://localhost:3000/votazioni
Authorization: Bearer {{TOKEN_OPERATORE}}

### Dettaglio votazione
GET http://localhost:3000/votazioni/{{VOTAZIONE_ID}}
Authorization: Bearer {{TOKEN_OPERATORE}}

### Riepilogo Votazione
GET http://localhost:3000/votazioni/{{VOTAZIONE_ID}}/riepilogo
Authorization: Bearer {{TOKEN_OPERATORE}}

### Modifica votazione (solo stato "bozza")
PATCH http://localhost:3000/votazioni/{{VOTAZIONE_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN_OPERATORE}}

{
  "titolo": "Votazione modificata",
  "descrizione": "Descrizione aggiornata"
}

### Pubblica votazione (bozza -> attivo)
PATCH http://localhost:3000/votazioni/{{VOTAZIONE_ID}}/publish
Authorization: Bearer {{TOKEN_OPERATORE}}

### Archivia votazione (concluso -> archiviato)
PATCH http://localhost:3000/votazioni/{{VOTAZIONE_ID}}/archive
Authorization: Bearer {{TOKEN_OPERATORE}}

### Eliminazione votazione (solo stato "bozza")
DELETE http://localhost:3000/votazioni/{{VOTAZIONE_ID}}
Authorization: Bearer {{TOKEN_OPERATORE}}


