@startuml Cittadino

skinparam classAttributeIconSize 0
skinparam classFontStyle bold
skinparam classFontSize 12
skinparam classBackgroundColor #F8F9FA
skinparam classBorderColor #0052A3
skinparam classHeaderBackgroundColor #0052A3
skinparam classHeaderFontColor #FFFFFF

class Cittadino {
  + _id : ObjectId
  + nome : String
  + cognome : String
  + dataNascita : Date
  + comuneResidenza : String
  + circoscrizione : String
  + ID_univoco_esterno : String <<unique>>
  + genere : String <<enum: Uomo, Donna>>
  + categoria : String <<enum: Lavoratore, Disoccupato, Pensionato, Studente, Altro>>
  + email : String <<unique>>
  + loggedIn : Boolean
  + profiloCompleto : Boolean
}

@enduml
