@startuml Operatore

skinparam classAttributeIconSize 0
skinparam classFontStyle bold
skinparam classFontSize 12
skinparam classBackgroundColor #F8F9FA
skinparam classBorderColor #0052A3
skinparam classHeaderBackgroundColor #0052A3
skinparam classHeaderFontColor #FFFFFF

class Operatore {
  + _id : ObjectId
  + username : String <<unique, required>>
  + password : String <<bcrypt, required>>
  + nome : String <<required>>
  + cognome : String <<required>>
  + isRoot : Boolean
  --
  + matchPassword(pwd) : Boolean
}

@enduml
